###
POST http://localhost:3000/api/heroe
Content-Type: application/json

{
    "nombre":"Matt Murdokc",
    "heroe":"Daredevil",
    "poder":"fuerza, e inteligtencia",
    "debilidad":"no se",
    "edad":"30",
    "foto":"https://1.bp.blogspot.com/-ohDAvcp9Dhc/XscaI_DDoDI/AAAAAAAB4Vk/m1Z2ccCi30IunsyG3tzEMnrqjS0S8IauwCLcBGAsYHQ/s1600/daredevil.jpg",
    "descripcion":"hombre que quedo ciego desde niño que le cayó líquidos radioactivos en los ojos"
}

###

GET http://localhost:3000/api/heroe/60e1e334426b4364e8707d62


###
PUT http://localhost:3000/api/heroe/60e1e334426b4364e8707d62
Content-Type: application/json

{
"nombre": "barry",
  "heroe": "flash",
  "poder": "velocidad",
  "debilidad": "otro velocista",
  "edad": 38
}

###

DELETE http://localhost:3000/api/heroe/60e1e334426b4364e8707d62

###
GET  http://localhost:3000/api/heroe